import type { MenuItem } from '@/types';

export const menuItems: MenuItem[] = [
  // ========== Pizza Mario ==========
  {
    id: 'pm-margherita',
    restaurantId: 'pizza-mario',
    name: 'Маргарита',
    description: 'Томатный соус, моцарелла, свежий базилик',
    price: 590,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80',
    category: 'Пицца',
    weight: '450 г',
  },
  {
    id: 'pm-pepperoni',
    restaurantId: 'pizza-mario',
    name: 'Пепперони',
    description: 'Томатный соус, моцарелла, пепперони, орегано',
    price: 690,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&q=80',
    category: 'Пицца',
    weight: '480 г',
  },
  {
    id: 'pm-four-cheese',
    restaurantId: 'pizza-mario',
    name: 'Четыре сыра',
    description: 'Моцарелла, дорблю, чеддер, пармезан',
    price: 750,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80',
    category: 'Пицца',
    weight: '470 г',
  },
  {
    id: 'pm-caesar',
    restaurantId: 'pizza-mario',
    name: 'Цезарь с курицей',
    description: 'Романо, курица, пармезан, гренки, соус цезарь',
    price: 420,
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400&q=80',
    category: 'Салаты',
    weight: '280 г',
  },
  {
    id: 'pm-tiramisu',
    restaurantId: 'pizza-mario',
    name: 'Тирамису',
    description: 'Классический итальянский десерт',
    price: 340,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80',
    category: 'Десерты',
    weight: '150 г',
  },
  {
    id: 'pm-cola',
    restaurantId: 'pizza-mario',
    name: 'Кола',
    description: 'Классическая кола, 0.5 л',
    price: 150,
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&q=80',
    category: 'Напитки',
    weight: '500 мл',
  },

  // ========== Sushi Zen ==========
  {
    id: 'sz-philadelphia',
    restaurantId: 'sushi-zen',
    name: 'Филадельфия',
    description: 'Лосось, сливочный сыр, огурец',
    price: 590,
    image: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=400&q=80',
    category: 'Суши',
    weight: '250 г / 8 шт',
  },
  {
    id: 'sz-california',
    restaurantId: 'sushi-zen',
    name: 'Калифорния',
    description: 'Краб, авокадо, огурец, икра тобико',
    price: 520,
    image: 'https://images.unsplash.com/photo-1615361200141-f45040f367be?w=400&q=80',
    category: 'Суши',
    weight: '230 г / 8 шт',
  },
  {
    id: 'sz-dragon',
    restaurantId: 'sushi-zen',
    name: 'Зелёный дракон',
    description: 'Угорь, авокадо, огурец, сыр',
    price: 640,
    image: 'https://images.unsplash.com/photo-1607301406259-dfb186e15de8?w=400&q=80',
    category: 'Суши',
    weight: '270 г / 8 шт',
  },
  {
    id: 'sz-miso',
    restaurantId: 'sushi-zen',
    name: 'Мисо-суп',
    description: 'Классический японский суп с тофу',
    price: 280,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80',
    category: 'Супы',
    weight: '300 мл',
  },
  {
    id: 'sz-green-tea',
    restaurantId: 'sushi-zen',
    name: 'Зелёный чай',
    description: 'Японский чай сенча',
    price: 180,
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400&q=80',
    category: 'Напитки',
    weight: '400 мл',
  },

  // ========== Burger House ==========
  {
    id: 'bh-cheeseburger',
    restaurantId: 'burger-house',
    name: 'Чизбургер',
    description: 'Говядина, чеддер, соус, булочка бриошь',
    price: 450,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80',
    category: 'Горячее',
    weight: '320 г',
  },
  {
    id: 'bh-double',
    restaurantId: 'burger-house',
    name: 'Двойной бургер',
    description: 'Две котлеты, двойной чеддер, бекон',
    price: 690,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&q=80',
    category: 'Горячее',
    weight: '450 г',
  },
  {
    id: 'bh-fries',
    restaurantId: 'burger-house',
    name: 'Картофель фри',
    description: 'Хрустящий картофель с солью',
    price: 200,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80',
    category: 'Горячее',
    weight: '150 г',
  },
  {
    id: 'bh-nuggets',
    restaurantId: 'burger-house',
    name: 'Наггетсы',
    description: 'Куриные наггетсы, 9 шт',
    price: 280,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&q=80',
    category: 'Горячее',
    weight: '180 г',
  },
  {
    id: 'bh-milkshake',
    restaurantId: 'burger-house',
    name: 'Молочный коктейль',
    description: 'Ванильный, шоколадный или клубничный',
    price: 250,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&q=80',
    category: 'Напитки',
    weight: '400 мл',
  },

  // ========== Wok Street ==========
  {
    id: 'ws-wok-chicken',
    restaurantId: 'wok-street',
    name: 'Wok с курицей',
    description: 'Рисовая лапша, курица, овощи, соус терияки',
    price: 420,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&q=80',
    category: 'Горячее',
    weight: '380 г',
  },
  {
    id: 'ws-wok-shrimp',
    restaurantId: 'wok-street',
    name: 'Wok с креветками',
    description: 'Рисовая лапша, тигровые креветки, овощи',
    price: 520,
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&q=80',
    category: 'Горячее',
    weight: '370 г',
  },
  {
    id: 'ws-dim-sum',
    restaurantId: 'wok-street',
    name: 'Дим-самы',
    description: 'Китайские пельмени на пару, 6 шт',
    price: 350,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&q=80',
    category: 'Горячее',
    weight: '220 г',
  },
  {
    id: 'ws-tom-yum',
    restaurantId: 'wok-street',
    name: 'Том Ям',
    description: 'Острый тайский суп с креветками',
    price: 480,
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400&q=80',
    category: 'Супы',
    weight: '400 мл',
  },

  // ========== Тбилиси ==========
  {
    id: 'tb-khinkali',
    restaurantId: 'tbilisi',
    name: 'Хинкали',
    description: 'Грузинские хинкали с говядиной, 5 шт',
    price: 380,
    image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&q=80',
    category: 'Горячее',
    weight: '350 г',
  },
  {
    id: 'tb-khachapuri',
    restaurantId: 'tbilisi',
    name: 'Хачапури по-аджарски',
    description: 'Лодочка из теста с сыром и яйцом',
    price: 490,
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=400&q=80',
    category: 'Горячее',
    weight: '450 г',
  },
  {
    id: 'tb-shashlik',
    restaurantId: 'tbilisi',
    name: 'Шашлык из свинины',
    description: 'Сочный шашлык с луком и зеленью',
    price: 620,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400&q=80',
    category: 'Горячее',
    weight: '300 г',
  },
  {
    id: 'tb-lobio',
    restaurantId: 'tbilisi',
    name: 'Лобио',
    description: 'Тушёная фасоль с орехами и специями',
    price: 340,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80',
    category: 'Горячее',
    weight: '280 г',
  },

  // ========== Coffee Lab ==========
  {
    id: 'cl-cappuccino',
    restaurantId: 'coffee-lab',
    name: 'Капучино',
    description: 'Двойной эспрессо с молочной пенкой',
    price: 220,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&q=80',
    category: 'Напитки',
    weight: '250 мл',
  },
  {
    id: 'cl-latte',
    restaurantId: 'coffee-lab',
    name: 'Латте',
    description: 'Мягкий кофе с молоком',
    price: 250,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80',
    category: 'Напитки',
    weight: '350 мл',
  },
  {
    id: 'cl-cheesecake',
    restaurantId: 'coffee-lab',
    name: 'Чизкейк',
    description: 'Классический чизкейк с ягодным соусом',
    price: 320,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&q=80',
    category: 'Десерты',
    weight: '140 г',
  },
  {
    id: 'cl-croissant',
    restaurantId: 'coffee-lab',
    name: 'Круассан',
    description: 'Свежий круассан с маслом',
    price: 180,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80',
    category: 'Десерты',
    weight: '90 г',
  },
    // ========== Pasta Bar ==========
    {
      id: 'pb-carbonara',
      restaurantId: 'pasta-bar',
      name: 'Паста Карбонара',
      description: 'Спагетти, гуанчале, яйцо, пармезан, перец',
      price: 590,
      image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&q=80',
      category: 'Горячее',
      weight: '350 г',
    },
    {
      id: 'pb-bolognese',
      restaurantId: 'pasta-bar',
      name: 'Паста Болоньезе',
      description: 'Тальятелле, говяжий фарш, томатный соус',
      price: 620,
      image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80',
      category: 'Горячее',
      weight: '380 г',
    },
    {
      id: 'pb-risotto',
      restaurantId: 'pasta-bar',
      name: 'Ризотто с грибами',
      description: 'Рис арборио, белые грибы, пармезан',
      price: 680,
      image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&q=80',
      category: 'Горячее',
      weight: '340 г',
    },
    {
      id: 'pb-bruschetta',
      restaurantId: 'pasta-bar',
      name: 'Брускетта',
      description: 'Хрустящий хлеб, томаты, базилик, чеснок',
      price: 290,
      image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&q=80',
      category: 'Салаты',
      weight: '180 г',
    },
  
    // ========== Roll Club ==========
    {
      id: 'rc-set-1',
      restaurantId: 'roll-club',
      name: 'Сет Филадельфия',
      description: 'Филадельфия, Калифорния, запечённый ролл',
      price: 1290,
      image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=400&q=80',
      category: 'Суши',
      weight: '1000 г / 24 шт',
    },
    {
      id: 'rc-unagi',
      restaurantId: 'roll-club',
      name: 'Ролл с угрём',
      description: 'Угорь, авокадо, сыр, соус унаги',
      price: 620,
      image: 'https://images.unsplash.com/photo-1607301406259-dfb186e15de8?w=400&q=80',
      category: 'Суши',
      weight: '250 г / 8 шт',
    },
    {
      id: 'rc-miso',
      restaurantId: 'roll-club',
      name: 'Мисо-суп с лососем',
      description: 'Классический суп с лососем и тофу',
      price: 320,
      image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80',
      category: 'Супы',
      weight: '350 мл',
    },
    {
      id: 'rc-edamame',
      restaurantId: 'roll-club',
      name: 'Эдамаме',
      description: 'Молодые соевые бобы с морской солью',
      price: 260,
      image: 'https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?w=400&q=80',
      category: 'Салаты',
      weight: '200 г',
    },
  
    // ========== Steak House ==========
    {
      id: 'sh-ribeye',
      restaurantId: 'steak-house',
      name: 'Стейк Рибай',
      description: 'Мраморная говядина, соль, перец, розмарин',
      price: 1980,
      image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&q=80',
      category: 'Горячее',
      weight: '350 г',
    },
    {
      id: 'sh-striploin',
      restaurantId: 'steak-house',
      name: 'Стриплойн',
      description: 'Стейк из тонкого края с овощами гриль',
      price: 1690,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
      category: 'Горячее',
      weight: '320 г',
    },
    {
      id: 'sh-caesar-beef',
      restaurantId: 'steak-house',
      name: 'Цезарь с говядиной',
      description: 'Романо, стейк, пармезан, соус',
      price: 590,
      image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400&q=80',
      category: 'Салаты',
      weight: '300 г',
    },
    {
      id: 'sh-wine',
      restaurantId: 'steak-house',
      name: 'Бокал красного вина',
      description: 'Сухое красное вино, 150 мл',
      price: 450,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80',
      category: 'Напитки',
      weight: '150 мл',
    },
  
    // ========== Noodle House ==========
    {
      id: 'nh-ramen-tonkotsu',
      restaurantId: 'noodle-house',
      name: 'Рамен Тонкоцу',
      description: 'Свиной бульон, лапша, яйцо, чашу',
      price: 520,
      image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80',
      category: 'Супы',
      weight: '500 мл',
    },
    {
      id: 'nh-ramen-miso',
      restaurantId: 'noodle-house',
      name: 'Рамен Мисо',
      description: 'Мисо-бульон, курица, кукуруза, нори',
      price: 490,
      image: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=400&q=80',
      category: 'Супы',
      weight: '500 мл',
    },
    {
      id: 'nh-gyoza',
      restaurantId: 'noodle-house',
      name: 'Гёдза',
      description: 'Японские пельмени с курицей, 6 шт',
      price: 380,
      image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&q=80',
      category: 'Горячее',
      weight: '240 г',
    },
    {
      id: 'nh-matcha',
      restaurantId: 'noodle-house',
      name: 'Матча-латте',
      description: 'Японский зелёный чай с молоком',
      price: 280,
      image: 'https://images.unsplash.com/photo-1536013455962-2f01a9c1c4a4?w=400&q=80',
      category: 'Напитки',
      weight: '350 мл',
    },
  
    // ========== Хинкальная №1 ==========
    {
      id: 'kh-khinkali-beef',
      restaurantId: 'khinkalnaya',
      name: 'Хинкали с говядиной',
      description: 'Сочные хинкали, 5 шт',
      price: 420,
      image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&q=80',
      category: 'Горячее',
      weight: '400 г',
    },
    {
      id: 'kh-khinkali-lamb',
      restaurantId: 'khinkalnaya',
      name: 'Хинкали с бараниной',
      description: 'Хинкали с ароматной бараниной, 5 шт',
      price: 490,
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80',
      category: 'Горячее',
      weight: '400 г',
    },
    {
      id: 'kh-kharcho',
      restaurantId: 'khinkalnaya',
      name: 'Суп Харчо',
      description: 'Острый грузинский суп с говядиной',
      price: 420,
      image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80',
      category: 'Супы',
      weight: '400 мл',
    },
    {
      id: 'kh-chakhokhbili',
      restaurantId: 'khinkalnaya',
      name: 'Чахохбили',
      description: 'Тушёная курица с томатами и зеленью',
      price: 580,
      image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&q=80',
      category: 'Горячее',
      weight: '350 г',
    },
  
    // ========== Bakery & Coffee ==========
    {
      id: 'bk-croissant-almond',
      restaurantId: 'bakery',
      name: 'Круассан с миндалём',
      description: 'Слоёный круассан с миндальным кремом',
      price: 260,
      image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80',
      category: 'Десерты',
      weight: '110 г',
    },
    {
      id: 'bk-cinnamon-roll',
      restaurantId: 'bakery',
      name: 'Синнабон',
      description: 'Булочка с корицей и глазурью',
      price: 240,
      image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=400&q=80',
      category: 'Десерты',
      weight: '130 г',
    },
    {
      id: 'bk-flat-white',
      restaurantId: 'bakery',
      name: 'Флэт Уайт',
      description: 'Двойной эспрессо с молоком',
      price: 240,
      image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400&q=80',
      category: 'Напитки',
      weight: '200 мл',
    },
    {
      id: 'bk-matcha-cake',
      restaurantId: 'bakery',
      name: 'Матча-чизкейк',
      description: 'Нежный чизкейк с матчей',
      price: 340,
      image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80',
      category: 'Десерты',
      weight: '140 г',
    },
];

export function getMenuByRestaurant(restaurantId: string): MenuItem[] {
  return menuItems.filter((item) => item.restaurantId === restaurantId);
}

export function getCategoriesForRestaurant(restaurantId: string): string[] {
  const items = getMenuByRestaurant(restaurantId);
  const categories = new Set(items.map((item) => item.category));
  return Array.from(categories);
}

